---

- name: install packages
  apt:
    name={{ item }}
    state=latest
  with_items:
    - snmp
    - snmpd

- name: allow snmp for localhost
  lineinfile:
    dest=/etc/snmp/snmpd.conf
    regexp='^#rocommunity public  localhost'
    line='rocommunity public  localhost'

- name: restart snmpd
  service:
    name=snmpd
    state=restarted
